version: '3.4'

services:

  # messaging service
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # product db for product catalog service
  auctiondb:
    container_name: auctiondb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  # order db for ordering service
  ordersdb:
    container_name: ordersdb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"

  # product catalog service
  auction.products:
    container_name: auctionproduct
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ProductDatabaseSettings__ConnectionString=mongodb://auctiondb:27017"
    depends_on:
      - auctiondb    
    ports:
      - "8000:80"  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    
  # auction/bidding service
  auction.auction:
    container_name: auctionauction
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuctionDatabaseSettings__ConnectionString=mongodb://auctiondb:27017"
      - "EventBus__HostName=rabbitmq"
    depends_on:
      - auctiondb 
      - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # ordering service
  auction.ordering:
    container_name: auctionordering
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderConnection=Data Source=ordersdb;Database=OrdersDB;User ID=sa;Password=Odb12345678"
      - "EventBus__HostName=rabbitmq"
    depends_on:
      - ordersdb
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "8002:80"

  # API Gateway
  onlineauction.apigateway:
    container_name: onlineauctionapigateway
    depends_on:
      - auction.products
      - auction.auction
      - auction.ordering
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro