version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management

  ordersdb:
    image: mcr.microsoft.com/mssql/server

  auctiondb: 
    image: mongo

  identitydb:
    image: mcr.microsoft.com/mssql/server

  auction.products:
    image: ${DOCKER_REGISTRY-}auctionproducts
    build:
      context: .
      dockerfile: Auction.Products/Dockerfile

  auction.auction:
    image: ${DOCKER_REGISTRY-}auctionauction
    build:
      context: .
      dockerfile: Auction.Auction/Dockerfile


  auction.ordering:
    image: ${DOCKER_REGISTRY-}auctionordering
    build:
      context: .
      dockerfile: Auction.Ordering/Dockerfile


  onlineauction.apigateway:
    image: ${DOCKER_REGISTRY-}onlineauctionapigateway
    build:
      context: .
      dockerfile: OnlineAuction.APIGateway/Dockerfile


#  onlineauction.webui:
#    image: ${DOCKER_REGISTRY-}onlineauctionwebui
#    build:
#      context: .
#      dockerfile: OnlineAuction.WebUI/Dockerfile

