version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine

  ordersdb:
    image: mcr.microsoft.com/mssql/server

  auctiondb: 
    image: mongo

  auction.products:
    image: ${DOCKER_REGISTRY-}auctionproducts
    build:
      context: .
      dockerfile: Auction.Products/Dockerfile

  auction.auction:
    image: ${DOCKER_REGISTRY-}auctionauction
    build:
      context: .
      dockerfile: Auction.Auction/Dockerfile

